# Generated by Django 4.2.5 on 2023-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_au_BAC', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Note_en_francais', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Note_en_philosophie', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Note_en_mathematiques', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Note_en_anglais', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Note_en_geographie', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Serie_du_BAC', models.IntegerField(choices=[(0, 'A4'), (1, 'D'), (2, 'C')])),
                ('filiere_desiree', models.IntegerField(choices=[(0, 'SEG'), (1, 'SID'), (2, 'HISTOIRE ET ARCHEOLOGIE'), (3, 'GEOGRAPHIE'), (4, 'LETTRE MODERNE'), (5, 'PHILOSOPHIE')])),
            ],
        ),
    ]
